Models/Document.cs
namespace DocumentProject.Models;

public class Document
{
    // public int Id { get; set; }
    // public string Name { get; set; }
    // public string Author { get; set; }
    // public string Image { get; set; }
    // public DateTime UpdateDate { get; set; }
    // public string Summary { get; set; }
    // public int Price { get; set; }
    //
    // public DateTime CreateAt { get; set; }
    public int Id { get; set; }
    public string Name { get; set; }
    public string Author { get; set; }
    public string Image { get; set; }
    public string Summary { get; set; }
    public DateTime UpdateDate { get; set; } // Ko hien thi form
    public int Price { get; set; } // // Ko hien thi form
    
    public ICollection<Chapter> Chapters { get; set; }
    public ICollection<DocumentCategory> DocumentCategories { get; set; }

    public DateTime CreatedAt { get; set; }

    public Document()
    {
        this.CreatedAt = DateTime.Now;
    }
}

Controllers/ChapterController.cs
using DocumentProject.Data;
using DocumentProject.Models;
using DocumentProject.Views.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace DocumentProject.Controllers;

public class ChapterController : Controller
{
    private ApplicationDbContext _db;
    
    public ChapterController(ApplicationDbContext db)
    {
        _db = db;
    }
    
    // public IActionResult Index()
    // {
    //     var chapters = _db.Chapters.ToList();
    //     return View(chapters);
    // }
    //
    // public IActionResult Detail(string id)
    // {
    //     int documentId = Int32.Parse(id);
    //     var documents = _db.Documents.Find(documentId);
    //     return View(documents);
    // }
    
    [HttpGet]
    public IActionResult Create(int id)
    {
        ChapterCreate chapterCreate = new ChapterCreate()
        {
            DocumentId = id
        };
        return View(chapterCreate);
    }
    
    [HttpPost]
    public IActionResult Create(ChapterCreate chapterCreate)
    {
        Document? documentInDb = _db.Documents.Find(chapterCreate.DocumentId);
        if (documentInDb == null)
        {
            return Content("Error");
        }
        Chapter chapter = new Chapter()
        {
            DocumentId = chapterCreate.DocumentId,
            Content =  chapterCreate.Content,
            Document = documentInDb
        };
        _db.Chapters.Add(chapter);
        _db.SaveChanges();
        return RedirectToAction("Detail", "Document", new { id = chapterCreate.DocumentId });
    }
    
    public IActionResult Detail(int id)
    {
        var chapter = _db.Chapters
            .Include(c => c.Document)
            .FirstOrDefault(d => d.Id == id);
        if (chapter != null)
        {
            var chapterRelated = _db.Chapters.Where(c => c.DocumentId == chapter.DocumentId).ToList();
            chapterRelated.Remove(chapter);
            ChapterDetail chapterDetail = new ChapterDetail()
            {
                Chapter = chapter,
                Chapters = chapterRelated
            };


            return View(chapterDetail);
        }
        return Content("Not find chapter");
    }

    public IActionResult Delete(int id)
    {
        var chapter = _db.Chapters
            .Include(c => c.Document)
            .FirstOrDefault(d => d.Id == id);
        var documentId = chapter.DocumentId;
        var chapters = _db.Chapters.Find(id);
        if (chapters != null)
        {
            _db.Chapters.Remove(chapters);
            _db.SaveChanges();
            
            //return RedirectToAction("Detail", "Chapters", "nextChapter");
            return RedirectToAction("Detail", "Document", new { id = documentId});
        }

        return RedirectToAction("Detail", "Document", new { id = documentId});
    }
    
    [HttpGet]
    public IActionResult Update(string id)
    {
        int chapterId = Int32.Parse(id);
        var chapters = _db.Chapters.Find(chapterId);
        ChapterUpdate formChapter = new ChapterUpdate()
        {
            Id = chapters.Id,
            Content = chapters.Content
        };
        return View(formChapter);
    }
    
    [HttpPost]
    public IActionResult Update(ChapterUpdate chapterUpdate)
    {
        var chapter = _db.Chapters.Find(chapterUpdate.Id);
        chapter.Content = chapterUpdate.Content;
        _db.SaveChanges();
        string chapterId = $"{chapterUpdate.Id}";
        return RedirectToAction("Detail", new { id = chapterId });
    }
}

Controllers/DocumentController.cs
using DocumentProject.Data;
using DocumentProject.Models;
using DocumentProject.Views.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace DocumentProject.Controllers;

[Authorize]
public class DocumentController : Controller
{
    private ApplicationDbContext _db;

    public DocumentController(ApplicationDbContext db)
    {
        _db = db;
    }
    
    //GET
    public IActionResult Index()
    {
        var documents = _db.Documents.ToList(); // SELECT * FROM DOCUMENTS
        return View(documents);
    }

    public IActionResult Detail(string id)
    {
        int documentId = Int32.Parse(id);
        var documents = _db.Documents.Find(documentId);
        if (documents == null)
        {
            return Content("No find document");
        }
        var chapters = _db.Chapters
            .FirstOrDefault(c => c.DocumentId == documentId);
        if (chapters == null)
        {
            documents.Chapters = null;
        }
        else
        {
            documents.Chapters = new List<Chapter>()
            {
                chapters
            };
        }
        return View(documents);
    }
    
    public IActionResult Delete(string id)
    {
        int documentId = Int32.Parse(id);
        var documents = _db.Documents.Find(documentId);
        if (documents != null)
        {
            _db.Documents.Remove(documents);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }
        // Noti
        return RedirectToAction("Index");
    }
    
    [HttpGet]
    public IActionResult Create()
    {
        DocumentCreate formDocument = new DocumentCreate();
        return View(formDocument);
    }
    
    [HttpPost]
    public IActionResult Create(DocumentCreate document)
    {
        Document newDocument = new Document()
        {
            Name = document.Name,
            Author = document.Author,
            Image = document.Image,
            Summary = document.Summary,
            Price = 20,
            UpdateDate = DateTime.Now
        };
        
        var savedDocument = _db.Documents.Add(newDocument);
        _db.SaveChanges();
        return RedirectToAction("Index");
    }
    
    [HttpGet]
    public IActionResult Update(string id)
    {
        int documentId = Int32.Parse(id);
        var documents = _db.Documents.Find(documentId);
        DocumentUpdate formDocument = new DocumentUpdate()
        {
            Id = documents.Id,
            Author = documents.Author,
            Image = documents.Image,
            Name = documents.Name,
            Price = documents.Price,
            Summary = documents.Summary
        };
        return View(formDocument);
    }
    
    [HttpPost]
    public IActionResult Update(DocumentUpdate documentUpdate)
    {
        var document = _db.Documents.Find(documentUpdate.Id);
        document.Author = documentUpdate.Author;
        document.Name = documentUpdate.Name;
        document.Image = documentUpdate.Image;
        document.Summary = documentUpdate.Summary;
        document.Price = documentUpdate.Price;
        document.UpdateDate = DateTime.Now;
        _db.SaveChanges();
        string docId = $"{documentUpdate.Id}";
        return RedirectToAction("Detail", new { id = docId });
    }
}

Views/Document/Create.cshtml
@model DocumentProject.Views.ViewModels.DocumentCreate

@{
    ViewBag.Title = "Form";
    Layout = "_Layout";
}

<h2>Form create Document</h2>
<form asp-action="Create" method="post">
    <label asp-for="Name">Name</label>
    <input type="text" asp-for="Name">
       <label asp-for="Author">Author</label>
    <input type="text" asp-for="Author">
       <label asp-for="Image">Image</label>
    <input type="text" asp-for="Image">
       <label asp-for="Summary">Summary</label>
    <input type="text" asp-for="Summary">
    <button type="submit">Save</button>
</form>

Views/Document/Detail.cshtml
@model Document

@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}

<button type="button">
    <a asp-action="Index">Back</a>
</button>
<button type="button">
    <a asp-action="Delete" asp-route-id="@Model.Id">Delete</a>
</button>
<button type="button">
    <a asp-action="Update" asp-route-id="@Model.Id">Update</a>
</button>
<button type="button">
    <a asp-controller="Chapter" asp-action="Create" asp-route-id="@Model.Id">Create chapter</a>
</button>
@{
    <div class="card">
        <img src="@Model.Image" alt="Avatar" style="width:300px;height: 300px">
        <div class="container">
            <h4>
                <b>
                    <a>@Model.Name</a>
                </b>
            </h4>
            <h5>
                <b>
                    <a>@Model.Id</a>
                </b>
            </h5>
            <p>@Model.Author</p>
            <p>@Model.Price</p>
            <p>@Model.Summary</p>
            <p>@Model.CreatedAt</p>
            <ul>
                <h5>Chapter</h5>
                @{
                    if (Model.Chapters == null)
                    {
                        <li>No chapter for document</li>
                    }
                    else
                    {
                        foreach (var chapter in Model.Chapters)
                        {
                            <li>
                                <a asp-controller="Chapter" asp-action="Detail" asp-route-id="@chapter.Id">@chapter.Content</a>
                            </li>
                        }
                    }
                }
            </ul>
        </div>
    </div>
}

Views/Document/Index.cshtml
@model List<Document>


@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}

<button type="button"><a asp-controller="Document" asp-action="Create">Create</a> </button>

@{
    foreach (var document in Model)
    {
        <div class="card">
            <img src="@document.Image" alt="Avatar" style="width:300px;height: 300px">
            <div class="container">
                <h4><b><a asp-action="Detail" asp-route-id="@document.Id">@document.Name</a></b></h4>
                <p>@document.Author</p>
                <p>@document.Summary</p>
                <p>@document.Price</p>
            </div>
        </div>
    }
}

Views/Document/Update.cshtml
@model DocumentProject.Views.ViewModels.DocumentUpdate

@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}

<h2>Form create Document</h2>
<form asp-action="Update" method="post">
    <label asp-for="Name">Name</label>
    <input type="text" asp-for="Name" value="@Model.Name">
    <label asp-for="Author">Author</label>
    <input type="text" asp-for="Author" value="@Model.Author">
    <label asp-for="Image">Image</label>
    <input type="text" asp-for="Image" value="@Model.Image">
    <label asp-for="Summary">Summary</label>
    <input type="text" asp-for="Summary" value="@Model.Summary">
    <label asp-for="Price">Summary</label>
    <input type="text" asp-for="Price" value="@Model.Price">
    <button type="submit">Save</button>
</form>